# Generated by Django 4.1.5 on 2023-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profession_header_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_img', models.ImageField(upload_to='images/area/', verbose_name='Изображение графика статистики по городам')),
                ('salary_table', models.TextField(verbose_name='Таблица ЗП по городам')),
                ('fraction_table', models.TextField(verbose_name='Таблица доли вакансий по городам')),
            ],
            options={
                'verbose_name': 'Статистика по городам',
                'verbose_name_plural': 'Статистики по городам',
            },
        ),
    ]
