# Generated by Django 4.1.5 on 2023-01-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_salarystatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStatisticsPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('plot', models.ImageField(upload_to='images/skills/', verbose_name='Изображение графика топ-10 навыков')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profession', verbose_name='Выбранная профессия')),
            ],
            options={
                'verbose_name': 'Статистика по навыкам за год',
                'verbose_name_plural': 'Статистики по навыкам',
            },
        ),
    ]
