# Generated by Django 4.1.5 on 2023-01-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skillstatisticsperyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillstatisticsperyear',
            old_name='plot',
            new_name='plot_img',
        ),
    ]
